name: update_docker_image
on:
  workflow_run:
    workflows: ["pycram_docker_ci"]
    types:
      - completed
  workflow_dispatch: # manual run
    inputs:
      manual_run:
        description: "build and push manually"
        type: boolean
        default: false
        required: false

# Runs if pycram_docker_ci workflow Wwa successful
jobs:
  build_and_push_docker_image:
    runs-on: ubuntu-latest
    if: ${{ (github.event.workflow_run.conclusion == 'success') || (github.event.inputs.manual_run)}}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: log into Docker Hub #Set repository secrets in github secrets
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./docker
          push: true
          tags: ${{ vars.DOCKER_IMAGE }}
